### ISSUE TITLE
"Missing notificaiton rule for schedule id" warning

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/UVPlugin-filesToCKAN#14]
When an execution of a pipeline with l-filesToCkan is triggered by the scheduler, the following warning is logged by l-filesToCkan: `Missing notificaiton rule for schedule id: 5`. However, when an execution of the same pipeline is triggered manually, no warning is logged.

Is this an issue of l-filesToCkan or of the scheduler?

Also note that there is a typo in "notificaiton" (=> "notification").

Context: ODN 1.1.0.

**Comment by ghost** [comment]
This is issue in UV/backend
